### ISSUE TITLE
configure option in docker

### ISSUE THREAD

**Issue by astrowalker2013** [leon-ai/leon#104]
Hello,

I try Leon and I succes to install by Docker
how ever I cannot change the option
i create a .env file and rebuit my docker but the option is not take account 
How to do that ?

Thankd in advence

**Comment by louistiti** [comment]
Hello @astrowalker2013,

Thanks for opening this issue. Indeed, with Docker you should edit the `.env.sample` file instead of the `.env` file. Because during the setup, with Docker the `.env` will be automatically replaced.

I will add this to the documentation or see if I can find an alternative to that.

Does it help?

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🐞 [1.0.0-beta.3] Take `.env` in consideration when using Docker](https://trello.com/c/Ih6oiUW9/283-%F0%9F%90%9E-100-beta3-take-env-in-consideration-when-using-docker)

**Comment by louistiti** [comment]
I've made a fix for it https://github.com/leon-ai/leon/commit/d38e6095f9b71467b8486430fba4bb7007ec4c5a.

Please:
1. Pull the `develop` branch.
2. Edit your `.env` file if you already have one.
3. Run `npm run docker:build`
4. Run `npm run docker:run`

Your `.env` file should now be used instead of the `.env.sample` one.

You can take a look at this issue to know more about why that happened https://github.com/leon-ai/leon/issues/50.

Let me know your thoughts.

**Comment by astrowalker2013** [comment]
Hello I test you proposition but I have an error
I pull the develope version I rebuild   a image of Leon with .env file but LEON doesnt launch


![image](https://user-images.githubusercontent.com/32897635/59149784-67658500-8a1a-11e9-99ac-05db36f6bf71.png)
my .env file is like 

`LEON_LANG=fr-FR
LEON_TTS=true
`
Best

**Comment by astrowalker2013** [comment]
I Understand the Issue, in my env file it miss other parmater 
I think it's important to have a sample file to help  the body to configure the application .

I create a personal env file with the doc and if you want I push on the project the envfile ? 
https://docs.getleon.ai/configuration.html#environment-variables
Is it enough or it miss other variable.

**Comment by louistiti** [comment]
Hello @astrowalker2013,

There is already a sample file: `.env.sample`. The `.env` file is generated during the setup of Leon based on the `.env.sample` one.

Since the last time, I've made some work on those files, please:
1. `git pull` the project
2. Run `npm install`
3. During the setup, Leon will ask you if you want to override the `.env`, reply `yes`
4. Edit your `.env` file if necessary
5. Run `npm run docker:build`
6. Run `npm run docker:run`

Let me know if that helps.

**Comment by louistiti** [comment]
I close this issue as I've made a fix for it.
