### ISSUE TITLE
Error: Command failed: /bin/sh -c pipenv install --skip-lock

### ISSUE THREAD

**Issue by superchino9000** [leon-ai/leon#126]
### Question
Hello! I am using Ubuntu 16.04. Has anyone seen or solved this problem?
After 'npm install' I get error message 'Error: Command failed: /bin/sh -c pipenv install --skip-lock'.

**Comment by louistiti** [comment]
Hello @superchino9000,

Thanks for asking! Have you installed Pipenv before installing?

**Comment by superchino9000** [comment]
Hi Louis, yes pipenv is installed.

**Comment by louistiti** [comment]
Alright, please provide the outputs of the following commands:

```bash
node --version
npm --version
pipenv --version
python --version
python3 --version
pipenv --where
pipenv run python --version
```

That will help to have a better understanding of your setup 😃

**Comment by superchino9000** [comment]
Ha I guess I did not install pipenv correctly. I used 'pip install pipenv', that didn't work.

node 10.16.0
npm 6.9.0
pipenv 'No such file or directory'
python 2.7.12
python3 3.6.8
pipenv 'No such file or directory'
pipenv run python 'No such file or directory'

Any advice? Thanks!

**Comment by louistiti** [comment]
Indeed 😃

Maybe that [How To](https://docs.getleon.ai/how-to/#how-to-install-pipenv) would help?

**Comment by superchino9000** [comment]
Of course, silly me!

I fixed the pipenv issue but after running 'npm install', error 'Command failed: /bin/sh -c pipenv install --skip-lock' still exists. 'npm install' also output 1 low severity vulnerability and running 'npm audit fix' did not fix it. Can the 'skip-lock error' be ignored?

On the brighter side, Leon ran!

node v10.16.0
npm v6.9.0
pipenv v2018.11.26
python v2.7.12
python3 v3.6.8
pipenv --where /home/jp
pipenv run python works!

**Comment by superchino9000** [comment]
Closing this, 'skip-lock' error hasn't been a major issue.

**Comment by louistiti** [comment]
Hey @superchino9000,

Sorry for the late reply (I'm currently focusing on another project for a while: [2aud.io](http://2aud.io)).

Does this `skip-lock` error block the install so you cannot go further?

I'll need to remove it in the future, as planned on the [roadmap](https://trello.com/c/9FkcudYo/253-%F0%9F%90%9E-remove-pipenv-skip-locking).

Regarding the low vulnerability, it is due to a Node.js dependency. I usually track them and solve them as you can see in the commits/issues. I'll hunt it once I'm done with the other project.

Do not hesitate if you have any questions! I'm always happy to chat :smile:
