### ISSUE TITLE
Any interest in PyNode support?

### ISSUE THREAD

**Issue by fridgerator** [leon-ai/leon#139]
### Proposal

I have written a native node module for node to python foreign function interface interoperability. https://github.com/fridgerator/pynode. It allows python function calls from node via c++ bindings.

[Here is a blog post](https://thecodinginterface.com/blog/bridging-nodejs-and-python-with-pynode/) about it being used with some ML python libraries.

I'm wondering if there is any interest in using PyNode for leon.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [✨ [1.0.0-beta.4] New bridges](https://trello.com/c/z9lNNYKY/241-%E2%9C%A8-100-beta4-new-bridges)

**Comment by louistiti** [comment]
Hello @fridgerator,

Well done and thanks for suggesting!

It might be indeed useful once we'll be integrating new [bridges](https://docs.getleon.ai/bridges.html) to have a compatibility of the current Python modules with a potential JavaScript bridge, so that every Python module will be available under the JavaScript bridge too.

**Comment by louistiti** [comment]
After considering the JavaScript bridge, skills will be executed via a child process or worker thread using Node.js.
