### ISSUE TITLE
bug report for the installation on Windows 10

### ISSUE THREAD

**Issue by die3oute** [leon-ai/leon#171]
### Specs

- Leon version: 1.0.0-beta.3
- OS (or browser) version: Windows 10.0.18363.720
- Node.js version: 12.16.1 (x64)
- Complete "npm run check" output: 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leon@1.0.0-beta.3 preinstall: `node scripts/setup/preinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leon@1.0.0-beta.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Utilisateur\AppData\Roaming\npm-cache\_logs\2020-03-16T00_09_04_066Z-debug.log
- (if using Docker) Complete "npm run docker:check" output:
- (optional) Leon package version:

I tried to "npm install" leon from the unzipped file and I obtained this. Do you have any idea of how I could solve this problem ?

I also tried with the most recent version of leon and had the same problem.

**Comment by tdevilleduc** [comment]
I started from scratch, 
forked repo, 
install npm latest LTS (12.16.1), 
execute 'npm install', 
had an error because of missing pipenv
execute pip install pipenv
execute npm install again

`
λ npm run check

> leon@1.0.0-beta.3 check c:\Users\Utilisateur\Documents\repository\leon
> babel-node scripts/run-check.js

⠋
---

.: CHECKING :.

➡ C:\Windows\system32\cmd.exe /q /s /c "node --version"
✔ v12.16.1

➡ C:\Windows\system32\cmd.exe /q /s /c "npm --version"
✔ 6.13.4

➡ C:\Windows\system32\cmd.exe /q /s /c "pipenv --version"
✔ pipenv, version 2018.11.26

➡ C:\Windows\system32\cmd.exe /q /s /c "pipenv --where"
✔ C:\Users\Utilisateur\Documents\repository\leon\bridges\python

➡ C:\Windows\system32\cmd.exe /q /s /c "pipenv run python --version"
✔ Python 3.8.1

➡ C:\Windows\system32\cmd.exe /q /s /c "pipenv run python bridges/python/main.py scripts/assets/query-object.json"
✔ {"package": "leon", "module": "randomnumber", "action": "run", "lang": "en", "input": "Give me a random number", "entities": [], "output": {"type": "end", "codes": ["success"], "speech": 92, "options": {}}}

➡ Classifier state
✔ Found and valid

➡ Amazon Polly TTS
❗ Amazon Polly TTS is not yet configured

➡ Google Cloud TTS/STT
❗ Google Cloud TTS/STT is not yet configured

➡ Watson TTS
❗ Watson TTS is not yet configured

➡ Offline TTS
❗ Cannot find bin/flite/flite. You can setup the offline TTS by running: "npm run setup:offline-tts"

➡ Watson STT
❗ Watson STT is not yet configured

➡ Offline STT
❗ Cannot find bin/deepspeech/lm.binary. You can setup the offline STT by running: "npm run setup:offline-stt"

---

.: REPORT :.

➡ Here is the diagnosis about your current setup
✔ Run
✔ Run modules
✔ Reply you by texting
❗ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
❗ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
❗ Offline speech-to-text

✔ Hooray! Leon can run correctly
➡ If you have some yellow warnings, it is all good. It means some entities are not yet configured
`

Everything seems fine;
Do you have python ?

**Comment by die3oute** [comment]
Thank you very much everything worked perfectly !

**Comment by tdevilleduc** [comment]
Did you do something special to make it work ?
Please close issue if everything is ok for you

**Comment by die3oute** [comment]
I just installed pipenv as you advised me to. and everything worked properly.
I close the issue thanks.
