### ISSUE TITLE
Wakeword after closing Snowboy service

### ISSUE THREAD

**Issue by silverdesignerdeveloper** [leon-ai/leon#236]
### Question
Hi how could I create a custom wakeword since the service you used kitt ai's "snowboy" has been permanently closed? Other services are paid, how can I create one for my voice assistant?

**Comment by louistiti** [comment]
Hello @silverdesignerdeveloper :wave:,

Thanks for asking. I have seen some GitHub repos like [this one](https://github.com/seasalt-ai/snowboy) where you can build your Snowboy wake word locally. Otherwise, you can also dig a bit deeper and take a look at [Porcupine](https://github.com/Picovoice/porcupine).

Support of multiple wake word detection engines is something that is planned for Leon, but not in a near future.

**Comment by louistiti** [comment]
Closing this issue as the answer has been provided. Feel free to reopen it if necessary.
