### ISSUE TITLE
Re-version to 0.x.x?

### ISSUE THREAD

**Issue by aikar** [leon-ai/leon#47]
I feel labeling this project as 1.0.0 to be deceptive, especially for a project this large in scope.

1.0.0 to most developers signals a 'ready for production use' mark for a projects lifecycle.

I would suggest following semantic versioning and start with 0.x.x.

**Comment by louistiti** [comment]
Hello @aikar,

Thanks for suggesting. However, please note the suffix containing the label `beta` as follows: `-beta.x`. It is completely [semver friendly](https://semver.org/#spec-item-9). I chose this versioning at the beginning because it has all the nodes I wanted for the project (TTS, STT, NLP, bridges, etc.).

Also, I just edited the [releases](https://github.com/leon-ai/leon/releases) to pre-releases.

**Comment by louistiti** [comment]
I close this issue as the answer has been provided.
