### ISSUE TITLE
Node.js Skill SDK

### ISSUE THREAD

**Issue by louistiti** [leon-ai/leon#483]
Having an SDK will drastically improve the developer experience when building new skills with JavaScript. It should be fully agnostic with the Python SDK.

The SDK should clearly be distinguished from the bridge at the file structure level.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [✨ [1.0.0-beta.9] Leon Node.js Skill SDK](https://trello.com/c/xZX4UG1h/488-%E2%9C%A8-100-beta9-leon-nodejs-skill-sdk)

**Comment by louistiti** [comment]
The Node.js SDK for building JavaScript skills is done. Code can be found [here](https://github.com/leon-ai/leon/tree/develop/bridges/nodejs/src/sdk).

**Comment by xuguoliang1964** [comment]
Dear Louis:


I tried like this:
1. do "git pull" to include your update code
2. command "leon create birth"
3. do "leon check"
4. modified .env to make change:LEON_STT=true....LEON_TTS=true
5.do "leon start"
 Then the problem is still there. It is obviously that the server is not running and ready to work.
















At 2023-05-18 21:23:24, "Louis Grenard" ***@***.***> wrote:

Closed #483 as completed.
