### ISSUE TITLE
Problem with modules

### ISSUE THREAD

**Issue by mortim59** [leon-ai/leon#5]
Hi ! I have an unexpected behavior, in fact when I type hello or any request that the assistant should understand it returns this message
```
Sorry, it seems I have a problem with the [module (ex: Whoami or Greeting)] of my Leon package!
```
I don't know if it's due to a bad installation of the packages.

Thanks.

**Comment by louistiti** [comment]
Hello @mortim59,

Thanks for your issue. Could you please use [this issue template](https://raw.githubusercontent.com/leon-ai/leon/develop/.github/ISSUE_TEMPLATE/BUG.md) to have a better understanding of the problem you are facing to?

**Comment by sh1ftsh** [comment]
---
name: 🐞 Bug Report
about: Report an unexpected problem or unintended behavior.
labels: bug
---



### Specs

- Leon version: 1.0.0-beta.0
- OS (or browser) version: Linux Manjaro (Firefox 65) 
- Node.js version: 10.10.0
- Complete "npm run check" output:
> leon@1.0.0-beta.0 check /media/aurel/main/lab/leon
> babel-node scripts/run-check.js

⠋
---

.: CHECKING :.

➡ /bin/sh -c node --version
✔ v10.10.0

➡ /bin/sh -c npm --version
✔ 6.5.0

➡ /bin/sh -c pipenv --version
✔ pipenv, version 2018.11.26

➡ /bin/sh -c pipenv --where
✔ /media/aurel/main/lab/leon/bridges/python

➡ /bin/sh -c pipenv run python --version
✔ Python 3.6.7

➡ /bin/sh -c pipenv run python bridges/python/main.py en leon randomnumber "Give me a random number"
✔ {"package": "leon", "module": "randomnumber", "lang": "en", "input": "Give me a random number", "output": {"type": "end", "code": "success", "speech": 58, "options": {}}}

➡ Classifier state
✔ Found and valid

➡ Amazon Polly TTS
❗ Amazon Polly TTS is not yet configured

➡ Google Cloud TTS/STT
❗ Google Cloud TTS/STT is not yet configured

➡ Watson TTS
❗ Watson TTS is not yet configured

➡ Offline TTS
❗ Cannot find bin/flite/flite. You can setup the offline TTS by running: "npm run setup:offline-tts"

➡ Watson STT
❗ Watson STT is not yet configured

➡ Offline STT
❗ Cannot find bin/deepspeech/lm.binary. You can setup the offline STT by running: "npm run setup:offline-stt"

---

.: REPORT :.

➡ Here is the diagnosis about your current setup
✔ Run
✔ Run modules
✔ Reply you by texting
❗ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
❗ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
❗ Offline speech-to-text

✔ Hooray! Leon can run correctly
➡ If you have some yellow warnings, it is all good. It means some entities are not yet configured

- (optional) Leon package version:

### Expected Behavior
I expect from leon to give me the answer  without the missing package error

### Actual Behavior
Sorry, it seems I have a problem with the [module (ex: Whoami or Greeting or Random Number)] of my Leon package!

### How Do We Reproduce?
Follow the installation procedure of leon
```sh
git clone -b master https://github.com/leon-ai/leon.git leon
cd leon
npm install
npm run check
npm run build
npm start
```

**Comment by louistiti** [comment]
Hello @sh1ftsh,

Thanks for your details. I was not able to reproduce the issue despite the fact I setup the same environment as you can see [here](https://i.gyazo.com/5b2fd100ff244316169c529bbaa837e6.png).

Leon triggers this scope when there is an error with the child process execution. You can find it in `server/src/core/brain.js` at the line 130.

Do you have anything in the `logs/errors.log` file?

**Comment by mortim59** [comment]
@louistiti Thank you

**Comment by mortim59** [comment]
---
name: 🐞 Bug Report 
about: Problem with modules
labels: bug
---
### Specs

- Leon version:
- OS (or browser) version: linux kernel version (4.15.0-45-generic)
- Node.js version: v10.8.0
- Complete "npm run check" output: 
```
> leon@1.0.0-beta.0 check /home/karim/leon
> babel-node scripts/run-check.js

⠋
---

.: CHECKING :.

✖ Error: Command failed: /bin/sh -c pipenv --version
/bin/sh: 1: pipenv: not found
```

### Expected Behavior
When I type hello or one of the existing commands by the wizard, it returns the corresponding message 

### Actual Behavior
I have error messages saying that a module is missing

### How Do We Reproduce?
```
git clone -b master https://github.com/leon-ai/leon.git leon
cd leon
npm install
npm run check
npm run build
npm start
```

**Comment by sh1ftsh** [comment]
@louistiti  yeah I do have some lines on logs/errors.log
the lines are like this
```
2019-02-13T11:05:39+01:00 - /bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
```

**Comment by louistiti** [comment]
@mortim59 thanks for your details. It seems Pipenv is not installed. Please [install it](https://docs.getleon.ai/how-to/#how-to-install-pipenv) first.

@sh1ftsh okay this warning is not related to the issue you mentioned previously. Unfortunately, I'm not able to reproduce this error 😞

**Comment by mortim59** [comment]
@louistiti ok thanks !

**Comment by louistiti** [comment]
Hello @sh1ftsh @mortim59,

Actually the warning mentioned in https://github.com/leon-ai/leon/issues/5#issuecomment-463138073 should cause that issue.

I invite you to take a look at [this answer](https://github.com/leon-ai/leon/issues/18#issuecomment-464538272) to fix it.

Please let me know if it solved the problem or not.

**Comment by louistiti** [comment]
I added a comment in the dotfiles.

- https://github.com/leon-ai/leon/commit/31658140367db27cc56058280e02e77eab169801
- https://github.com/leon-ai/leon/commit/1d559070e269250497d3ce187ce853b472551b50
