### ISSUE TITLE
This whole project is just broken

### ISSUE THREAD

**Issue by Magnusretrotech** [leon-ai/leon#532]
Full of deprecated npm packages, always gives errors when you follow the instructions.

You need to create a plug-and-play Docker container. Please, I want to be able to do `sudo docker run leon-ai/leon` and it pulls from docker hub, deploys and works.

**Comment by louistiti** [comment]
The `develop` branch is currently experiencing issues due to major changes. In contrast, the `master` branch is relatively stable, although it's still in beta. I recommend taking a closer look at the README and staying up-to-date with announcements on our Discord channel to get a better understanding of the changes. If you're experiencing urgent issues, feel free to fork the project and make improvements.
